import express from 'express'
import { createServer } from 'http'
import { Server as SocketServer } from 'socket.io'
import path from 'path'
import { fileURLToPath } from 'url'
import type { Logger } from '../utils/logger.js'
import type { DiscoveredDevice } from '../scanner/arp.js'
import type { NetworkSegment } from '../api/client.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

export interface AgentState {
  agentName: string
  dashboardUrl: string
  isConnected: boolean
  isRealtimeConnected: boolean
  lastHeartbeat: Date | null
  segments: Map<string, SegmentState>
  discoveredDevices: Map<string, DiscoveredDevice>
  deviceStatuses: Map<string, DeviceStatus>
  recentLogs: LogEntry[]
  // Version info
  currentVersion: string
  latestVersion: string | null
  upgradeAvailable: boolean
}

export interface SegmentState {
  segment: NetworkSegment
  isScanning: boolean
  lastScanAt: Date | null
  deviceCount: number
  progress: number
  isAutoGenerated?: boolean
}

export interface LogEntry {
  timestamp: Date
  level: 'info' | 'warn' | 'error' | 'debug'
  message: string
}

export interface DeviceStatus {
  ip_address: string
  status: 'online' | 'offline' | 'degraded' | 'unknown'
  response_time_ms: number | null
  last_check: Date
  error?: string
}

export class AgentUI {
  private app: express.Application
  private server: ReturnType<typeof createServer>
  private io: SocketServer
  private logger: Logger
  private state: AgentState
  private scanCallbacks: Map<string, () => Promise<void>> = new Map()
  private pingDashboardCallback: (() => Promise<void>) | null = null

  constructor(logger: Logger, agentName: string, dashboardUrl: string) {
    this.logger = logger
    this.app = express()
    this.server = createServer(this.app)
    this.io = new SocketServer(this.server, {
      cors: { origin: '*' },
      pingInterval: 15000,    // 15 seconds - detect dead connections faster
      pingTimeout: 45000,     // 45 seconds - allow for slow networks
      connectTimeout: 10000,  // 10 seconds - faster connection timeout
    })

    this.state = {
      agentName,
      dashboardUrl,
      isConnected: false,
      isRealtimeConnected: false,
      lastHeartbeat: null,
      segments: new Map(),
      discoveredDevices: new Map(),
      deviceStatuses: new Map(),
      recentLogs: [],
      // Version info - will be updated on heartbeat
      currentVersion: '0.0.0',
      latestVersion: null,
      upgradeAvailable: false,
    }

    this.setupRoutes()
    this.setupSocketIO()
  }

  private setupRoutes() {
    // Serve static files
    this.app.use(express.static(path.join(__dirname, 'public')))

    // API routes
    this.app.get('/api/status', (req, res) => {
      res.json({
        agentName: this.state.agentName,
        dashboardUrl: this.state.dashboardUrl,
        isConnected: this.state.isConnected,
        isRealtimeConnected: this.state.isRealtimeConnected,
        lastHeartbeat: this.state.lastHeartbeat,
        segmentCount: this.state.segments.size,
        deviceCount: this.state.discoveredDevices.size,
        currentVersion: this.state.currentVersion,
        latestVersion: this.state.latestVersion,
        upgradeAvailable: this.state.upgradeAvailable,
      })
    })

    this.app.get('/api/segments', (req, res) => {
      const segments = Array.from(this.state.segments.values()).map((s) => ({
        id: s.segment.id,
        name: s.segment.name,
        cidr: s.segment.cidr,
        scanInterval: s.segment.scan_interval_seconds,
        isScanning: s.isScanning,
        lastScanAt: s.lastScanAt,
        deviceCount: s.deviceCount,
        progress: s.progress,
      }))
      res.json({ segments })
    })

    this.app.get('/api/devices', (req, res) => {
      const devices = Array.from(this.state.discoveredDevices.values())
      res.json({ devices })
    })

    this.app.get('/api/logs', (req, res) => {
      res.json({ logs: this.state.recentLogs.slice(-100) })
    })

    this.app.post('/api/scan/:segmentId', async (req, res) => {
      const { segmentId } = req.params
      const callback = this.scanCallbacks.get(segmentId)

      if (!callback) {
        res.status(404).json({ error: 'Segment not found' })
        return
      }

      try {
        // Trigger scan in background
        callback().catch((err) => this.logger.error(`Manual scan failed: ${err}`))
        res.json({ success: true, message: 'Scan triggered' })
      } catch (error) {
        res.status(500).json({ error: 'Failed to trigger scan' })
      }
    })

    // Serve index.html for root
    this.app.get('/', (req, res) => {
      res.sendFile(path.join(__dirname, 'public', 'index.html'))
    })
  }

  private setupSocketIO() {
    this.io.on('connection', (socket) => {
      this.logger.debug(`UI client connected: ${socket.id}`)

      // Send current state
      socket.emit('state', this.getStateSnapshot())

      socket.on('disconnect', () => {
        this.logger.debug(`UI client disconnected: ${socket.id}`)
      })

      socket.on('triggerScan', async (segmentId: string) => {
        const callback = this.scanCallbacks.get(segmentId)
        if (callback) {
          callback().catch((err) => this.logger.error(`Manual scan failed: ${err}`))
        }
      })

      // Handle ping dashboard request from UI
      socket.on('pingDashboard', async () => {
        this.logger.info('Ping dashboard requested from UI')
        if (this.pingDashboardCallback) {
          this.pingDashboardCallback().catch((err) => {
            this.logger.error(`Ping dashboard failed: ${err}`)
          })
        }
      })
    })
  }

  private getStateSnapshot() {
    return {
      agentName: this.state.agentName,
      dashboardUrl: this.state.dashboardUrl,
      isConnected: this.state.isConnected,
      isRealtimeConnected: this.state.isRealtimeConnected,
      lastHeartbeat: this.state.lastHeartbeat,
      segments: Array.from(this.state.segments.values()).map((s) => ({
        id: s.segment.id,
        name: s.segment.name,
        cidr: s.segment.cidr,
        scanInterval: s.segment.scan_interval_seconds,
        isScanning: s.isScanning,
        lastScanAt: s.lastScanAt,
        deviceCount: s.deviceCount,
        progress: s.progress,
        isAutoGenerated: s.isAutoGenerated || s.segment.is_auto_registered || false,
      })),
      devices: Array.from(this.state.discoveredDevices.values()),
      deviceStatuses: Array.from(this.state.deviceStatuses.values()),
      logs: this.state.recentLogs.slice(-50),
      currentVersion: this.state.currentVersion,
      latestVersion: this.state.latestVersion,
      upgradeAvailable: this.state.upgradeAvailable,
    }
  }

  // Public methods to update state
  updateConnectionStatus(isConnected: boolean) {
    this.state.isConnected = isConnected
    this.io.emit('connectionStatus', isConnected)
  }

  updateRealtimeStatus(isConnected: boolean) {
    this.state.isRealtimeConnected = isConnected
    this.io.emit('realtimeStatus', isConnected)
  }

  updateHeartbeat() {
    this.state.lastHeartbeat = new Date()
    this.io.emit('heartbeat', this.state.lastHeartbeat)
  }

  updateVersionInfo(currentVersion: string, latestVersion?: string, upgradeAvailable?: boolean) {
    this.state.currentVersion = currentVersion
    this.state.latestVersion = latestVersion || null
    this.state.upgradeAvailable = upgradeAvailable || false
    this.io.emit('versionInfo', {
      currentVersion: this.state.currentVersion,
      latestVersion: this.state.latestVersion,
      upgradeAvailable: this.state.upgradeAvailable,
    })
  }

  updateSegments(segments: NetworkSegment[]) {
    for (const segment of segments) {
      if (!this.state.segments.has(segment.id)) {
        this.state.segments.set(segment.id, {
          segment,
          isScanning: false,
          lastScanAt: null,
          deviceCount: 0,
          progress: 0,
          isAutoGenerated: segment.is_auto_registered || false,
        })
      } else {
        const state = this.state.segments.get(segment.id)!
        state.segment = segment
        state.isAutoGenerated = segment.is_auto_registered || state.isAutoGenerated
      }
    }

    // Remove segments no longer assigned
    const removedSegmentIds: string[] = []
    for (const [id] of this.state.segments) {
      if (!segments.find((s) => s.id === id)) {
        this.state.segments.delete(id)
        removedSegmentIds.push(id)
      }
    }

    // Clean up device statuses for removed segments
    if (removedSegmentIds.length > 0) {
      this.cleanupDeviceStatuses(removedSegmentIds)
    }

    this.io.emit('segments', this.getStateSnapshot().segments)
  }

  /**
   * Clean up device statuses that belong to removed segments
   * This prevents stale data and memory leaks
   */
  private cleanupDeviceStatuses(removedSegmentIds: string[]): void {
    // Get the CIDRs of removed segments (we need to track which devices belonged to them)
    // For now, we'll clean up all device statuses when segments are removed
    // since we don't track which device belongs to which segment in the UI state
    const devicesInRemovedSegments = new Set<string>()

    // Check if any discovered devices no longer belong to any active segment
    // This is a simplified approach - remove all devices whose segments are gone
    for (const [ip, device] of this.state.discoveredDevices) {
      // If we have segment tracking per device, we could be more precise
      // For now, just log and let the next scan repopulate
      devicesInRemovedSegments.add(ip)
    }

    // Remove device statuses for devices in removed segments
    let cleanedCount = 0
    for (const ip of devicesInRemovedSegments) {
      if (this.state.deviceStatuses.has(ip)) {
        this.state.deviceStatuses.delete(ip)
        this.state.discoveredDevices.delete(ip)
        cleanedCount++
      }
    }

    if (cleanedCount > 0) {
      this.logger.debug(`Cleaned up ${cleanedCount} device statuses after segment removal`)
      // Emit updated device list
      this.io.emit('devices', Array.from(this.state.discoveredDevices.values()))
      this.io.emit('deviceStatuses', Array.from(this.state.deviceStatuses.values()))
    }
  }

  setScanCallback(segmentId: string, callback: () => Promise<void>) {
    this.scanCallbacks.set(segmentId, callback)
  }

  setPingDashboardCallback(callback: () => Promise<void>) {
    this.pingDashboardCallback = callback
  }

  showPingReceived() {
    this.logger.debug('Emitting pingReceived to UI')
    this.io.emit('pingReceived')
  }

  updateScanProgress(segmentId: string, progress: number, isScanning: boolean) {
    const state = this.state.segments.get(segmentId)
    if (state) {
      state.progress = progress
      state.isScanning = isScanning
      if (!isScanning && progress === 100) {
        state.lastScanAt = new Date()
      }
      this.io.emit('scanProgress', { segmentId, progress, isScanning })
    }
  }

  updateDevices(devices: DiscoveredDevice[]) {
    for (const device of devices) {
      this.state.discoveredDevices.set(device.ip_address, device)
    }

    // Update segment device counts
    for (const [, state] of this.state.segments) {
      state.deviceCount = devices.filter(
        (d) => d.ip_address // Count all devices for now
      ).length
    }

    this.io.emit('devices', Array.from(this.state.discoveredDevices.values()))
  }

  updateDeviceStatuses(statuses: DeviceStatus[]) {
    for (const status of statuses) {
      this.state.deviceStatuses.set(status.ip_address, status)
    }
    this.io.emit('deviceStatuses', Array.from(this.state.deviceStatuses.values()))
  }

  addLog(level: LogEntry['level'], message: string) {
    const entry: LogEntry = {
      timestamp: new Date(),
      level,
      message,
    }
    this.state.recentLogs.push(entry)
    if (this.state.recentLogs.length > 200) {
      this.state.recentLogs = this.state.recentLogs.slice(-100)
    }
    this.io.emit('log', entry)
  }

  async start(port = 3001): Promise<void> {
    return new Promise((resolve) => {
      this.server.listen(port, () => {
        this.logger.info(`Agent UI running at http://localhost:${port}`)
        resolve()
      })
    })
  }

  stop() {
    this.server.close()
  }
}
